import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { minify } from 'terser';

const inputFiles = [
  'assets/js/plugins/jquery.fitvids.js',
  'assets/js/plugins/jquery.magnific-popup.js',
  'assets/js/_main.js',
];
const outputFile = 'assets/js/scripts.min.js';

const source = await Promise.all(inputFiles.map((file) => readFile(file, 'utf8')));
const banner = '/*! Generated by npm run build:js. Edit assets/js/plugins/*.js or assets/js/_main.js. */\n';
const result = await minify(source.join('\n'), {
  compress: true,
  mangle: true,
  output: {
    comments: /^!/,
  },
});

if (!result.code) {
  throw new Error('Terser did not generate output.');
}

await mkdir(dirname(outputFile), { recursive: true });
await writeFile(outputFile, `${banner}${result.code}\n`);
